### ISSUE TITLE
PHP example with ServiceAccountCredentials class vs keyFilePath

### ISSUE THREAD

**Issue by razvanphp** [google-wallet/rest-samples#112]
Would it make more sense to use the `ServiceAccountCredentials` instance to retrieve the private key and client_email for signing the JWT token? Is this even possible?

I see it is instantiated in the demo...
https://github.com/google-wallet/rest-samples/blob/82f5e79e5f490b5b5175392d3935e4ebbc369a04/php/demo_generic.php#L66-L69

... but never used:
https://github.com/google-wallet/rest-samples/blob/82f5e79e5f490b5b5175392d3935e4ebbc369a04/php/demo_generic.php#L740-L756

Asking because I'm trying to make my code as flexible as possible, for example using other authentication methods like in Google App Engine or GKE service account, I guess those don't really need the service account json file, right?

Thank you for clarification!
R

**Comment by stephenmcd** [comment]
Yes that makes sense, the samples in most of the other languages do this.

**Comment by razvanphp** [comment]
Great, but how to do that, exactly?

For `client_email` we could use `ServiceAccountCredentials::getClientName()`, but what about the `private_key`?

We can't access `auth` object as it is [private](https://github.com/googleapis/google-auth-library-php/blob/3031d2c616902d514867953ede8688d2914d5b11/src/Credentials/ServiceAccountCredentials.php#L73)...

I see that java has `((ServiceAccountCredentials) credentials).getClientEmail()` and `((ServiceAccountCredentials) credentials).getPrivateKey())`, but there are no such methods in the PHP version.

Can we contribute this?

Also, it would be best if the JWT signing happens inside this class too, can we use this?
https://github.com/googleapis/google-auth-library-php/blob/3031d2c616902d514867953ede8688d2914d5b11/src/OAuth2.php#L573-L578

**Comment by stephenmcd** [comment]
Thanks for the detail - that would explain why these samples load the private key separately.

As for contributing back to the PHP lib, please feel free to raise it on that project - if it makes sense to the maintainers and it ends up being released, then we can revisit the changes in these samples too.

I'll close this issue for now since at this stage it's not possible given the restriction of the PHP lib, but we can re-open if it becomes possible.

**Comment by bshaffer** [comment]
> I'll close this issue for now since at this stage it's not possible given the restriction of the PHP lib, but we can re-open if it becomes possible.

What restrictions are you referring to? I don't think you're using the client library properly. The client libraries already support Service Account Credentials (and self-signed JWTs). 

As @razvanphp has mentioned, you're creating credentials but then not using them. IF you want to use custom credentials, you need to pass these into the `Google\Client` instance (please use `Google\Client` instead of `Google_Client`, the latter is deprecated). 

```php
$client = new Google\Client(['credentials' => $credentials]);
```

If you want to use self-signed JWTs, just call `useJwtAccessWithScope()` on the credentials object before passing it in:

```php
$credentials = new ServiceAccountCredentials($scope, $this->keyFilePath); 
$credentials->useJwtAccessWithScope();
$client = new Google\Client(['credentials' => $credentials]);
```

Since you're passing in the auth config file using `$client->setAuthConfig()`, you **do not need to do anything else at all**. But if you WANT to pass in custom credentials, do the above instead.

**Comment by razvanphp** [comment]
But this will mean one HTTP request extra for each API call (to fetch the token), why when you can locally sign them with the private key? Also, you cannot edit the other parameters of the token like `Origin` when using the Auth SDK, you NEED to sign locally.

**Comment by bshaffer** [comment]
@razvanphp no, you won't need to make an additional http request, you just need to call `useJwtAccessWithScope` on the credentials class and it will use self signed JWTs (as I have in the example above) and not make an authentication request.

We also can (and probably should) make the service account credentials use this by default for this client library, but in the meantime the above will work.

**Comment by razvanphp** [comment]
then why not instantiate directly `ServiceAccountJwtAccessCredentials`?
```
$this->credentials = new ServiceAccountJwtAccessCredentials(
      $this->keyFilePath,
      Walletobjects::WALLET_OBJECT_ISSUER
    );

    // Initialize Google Wallet API service
    $this->client = new GoogleClient(['credentials' => $this->credentials]);
    $this->client->setApplicationName('APPLICATION_NAME');
    $this->client->setScopes(Walletobjects::WALLET_OBJECT_ISSUER);

    $this->service = new Walletobjects($this->client);
```
just tested it and it works, not sure if we need to set the scope on the client if we put it in the credentials.

BUT, this solves the API requests to google directly for adding and updating passes, but can't be used for creating the "Add to Wallet" button links, since those are displayed to the end-user frontend.

Maybe we can add the `getPrivateKey()` to this class too/instead or we add a new method it it to sign/create the JWT token inside the auth lib.

**Comment by bshaffer** [comment]
That looks good to me as well! 

I believe the reason that Self-Signed JWT is not default behavior is simply because there are so many APIs (more than 300) that we weren't confident they would all work as expected.

We should at the very least add a feature for a flag or function that enables the SSJWTs, so that you don't need to manually create them as you're doing above. Something like this, for instance:

```php
// in the constructor
$client = new Google\Client(['use_self_signed_jwt' => true]);
// in a method
$client->useSelfSignedJwt(true);
```
